version: "3.9"

services:
  app:
    image: IMAGE_PLACEHOLDER   # Actions에서 최신 태그로 치환
    container_name: hackathon-app
    env_file:
      - .env
    depends_on:
      - db
    networks: [hacknet]
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: hackathon-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [hacknet]
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: hackathon-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [hacknet]
    restart: unless-stopped

volumes:
  pgdata:

networks:
  hacknet:
    driver: bridge
