server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: farmland-matching-BE
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins:
            - http://localhost:3000
            - http://43.203.207.57
          allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
          allowed-headers: ["*"]
          allow-credentials: false
          max-age: 3600

ai:
  base-url: ${AI_BASE_URL:http://host.docker.internal:8000}
  connect-timeout-ms: 3000
  read-timeout-ms: 15000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
