db:
  name: farmland
  username: root
  password: mite

supabase:
  url: "https://zdvgfsiiimjtjfcaedvi.supabase.co"
  anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkdmdmc2lpaW1qdGpmY2FlZHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTcxNDAsImV4cCI6MjA3MDE5MzE0MH0.h2F2RHHdyJipm8cV4T3gjW6u8eop0tOXo1TlkVmbJro"
  bucket: "seok"