package com.seokhyeon2356.farmlandmatchingbe.farmland.dto;

import org.springframework.web.multipart.MultipartFile;

public record SellerFarmlandUpdateReq(
        String landName,
        String landAddress,
        String landRoadAddress,
        String landNumber,
        Double landLat,
        Double landLng,
        String landCrop,
        Integer landArea,
        String soiltype,
        String waterSource,
        String ownerName,
        Integer ownerAge,
        String ownerAddress,
        String landWater,
        String landElec,
        String landMachine,
        String landStorage,
        String landHouse,
        String landFence,
        String landRoad,
        String landWellRoad,
        String landBus,
        String landCar,
        String landTrade,
        String landMatch,
        Integer landPrice,
        String landWhen,
        String landWhy,
        String landComent,
        MultipartFile landImage,
        MultipartFile landRegister,
        MultipartFile landCadastre,
        MultipartFile landCertification
) {}
